// <auto-generated>
// This file was generated from wayland.xml
// Stability: Core
// Link: https://wayland.app/protocols/wayland
// </auto-generated>

#nullable enable

namespace WaylandDotnet;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// wl_buffer
/// <para> content for a wl_surface </para>
/// <para> Version: 1 </para>
/// <see>https://wayland.app/protocols/wayland/#wl_buffer</see>
/// </summary>
public sealed partial class WlBuffer : WaylandObject, IWaylandObjectFactory<WlBuffer>
{
    /// <summary> Wayland interface name for wl_buffer. </summary>
    public const string InterfaceName = "wl_buffer";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "wl_buffer";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 1;

    private bool disposed;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing wl_buffer proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public WlBuffer(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary>
    /// Compositor releases buffer
    /// <para>
    ///
    /// Sent when this wl_buffer is no longer used by the compositor.
    ///
    /// For more information on when release events may or may not be sent,
    /// and what consequences it has, please see the description of
    /// wl_surface.attach.
    ///
    /// If a client receives a release event before the frame callback
    /// requested in the same wl_surface.commit that attaches this
    /// wl_buffer to a surface, then the client is immediately free to
    /// reuse the buffer and its backing storage, and does not need a
    /// second buffer for the next surface content update. Typically
    /// this is possible, when the compositor maintains a copy of the
    /// wl_surface contents, e.g. as a GL texture. This is an important
    /// optimization for GL(ES) compositors with wl_shm clients.
    /// 
    /// </para>
    /// </summary>
    public delegate void ReleaseHandler();

    private ReleaseHandler? _onRelease;

    /// <summary>
    /// Compositor releases buffer
    /// <para>
    ///
    /// Sent when this wl_buffer is no longer used by the compositor.
    ///
    /// For more information on when release events may or may not be sent,
    /// and what consequences it has, please see the description of
    /// wl_surface.attach.
    ///
    /// If a client receives a release event before the frame callback
    /// requested in the same wl_surface.commit that attaches this
    /// wl_buffer to a surface, then the client is immediately free to
    /// reuse the buffer and its backing storage, and does not need a
    /// second buffer for the next surface content update. Typically
    /// this is possible, when the compositor maintains a copy of the
    /// wl_surface contents, e.g. as a GL texture. This is an important
    /// optimization for GL(ES) compositors with wl_shm clients.
    /// 
    /// </para>
    /// </summary>
    public event ReleaseHandler? OnRelease
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onRelease += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onRelease -= value;
        }
    }

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to wl_buffer");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (WlBuffer)handle.Target!;

            switch (opcode)
            {
                case 0: // release
                    if (obj._onRelease != null)
                    {
                        obj._onRelease?.Invoke();
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }
    /// <summary>
    /// Destroy a buffer
    /// <para>
    /// <br/>
    /// Destroy a buffer. If and how you need to release the backing<br/>
    /// storage is defined by the buffer factory interface.<br/>
    /// <br/>
    /// For possible side-effects to a surface, see wl_surface.attach.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary> Creates a WlBuffer wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new WlBuffer instance.</returns>
    public static WlBuffer Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new WlBuffer(handle, display);
    }
}
