// <auto-generated>
// This file was generated from wayland.xml
// Stability: Core
// Link: https://wayland.app/protocols/wayland
// </auto-generated>

#nullable enable

namespace WaylandDotnet;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// wl_compositor
/// <para> the compositor singleton </para>
/// <para> Version: 7 </para>
/// <see>https://wayland.app/protocols/wayland/#wl_compositor</see>
/// </summary>
public sealed partial class WlCompositor : WaylandObject, IWaylandObjectFactory<WlCompositor>
{
    /// <summary> Wayland interface name for wl_compositor. </summary>
    public const string InterfaceName = "wl_compositor";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "wl_compositor";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 7;

    private bool disposed;

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing wl_compositor proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public WlCompositor(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary>
    /// Create new surface
    /// <para>
    /// <br/>
    /// Ask the compositor to create a new surface.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe WlSurface CreateSurface()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].o = (WlObject*)IntPtr.Zero;

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.WlSurface,
            (uint)WaylandInterfaces.WlSurface->Version,
            0,
            (nint)args
        );

        return new WlSurface(newProxy, Display);
    }

    /// <summary>
    /// Create new region
    /// <para>
    /// <br/>
    /// Ask the compositor to create a new region.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe WlRegion CreateRegion()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].o = (WlObject*)IntPtr.Zero;

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.WlRegion,
            (uint)WaylandInterfaces.WlRegion->Version,
            0,
            (nint)args
        );

        return new WlRegion(newProxy);
    }

    /// <summary>
    /// Destroy wl_compositor
    /// <para>
    /// <br/>
    /// This request destroys the wl_compositor. This has no effect on any other objects.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Release()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary> Creates a WlCompositor wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new WlCompositor instance.</returns>
    public static WlCompositor Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new WlCompositor(handle, display);
    }
}
