// <auto-generated>
// This file was generated from wayland.xml
// Stability: Core
// Link: https://wayland.app/protocols/wayland
// </auto-generated>

#nullable enable

namespace WaylandDotnet;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// wl_registry
/// <para> global registry object </para>
/// <para> Version: 1 </para>
/// <see>https://wayland.app/protocols/wayland/#wl_registry</see>
/// </summary>
public sealed partial class WlRegistry : WaylandObject, IWaylandObjectFactory<WlRegistry>
{
    /// <summary> Wayland interface name for wl_registry. </summary>
    public const string InterfaceName = "wl_registry";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "wl_registry";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 1;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing wl_registry proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public WlRegistry(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary>
    /// Announce global object
    /// <para>
    ///
    /// Notify the client of global objects.
    ///
    /// The event notifies the client that a global object with
    /// the given name is now available, and it implements the
    /// given version of the given interface.
    /// 
    /// </para>
    /// </summary>
    public delegate void GlobalHandler(uint name, string _interface, uint version);

    private GlobalHandler? _onGlobal;

    /// <summary>
    /// Announce global object
    /// <para>
    ///
    /// Notify the client of global objects.
    ///
    /// The event notifies the client that a global object with
    /// the given name is now available, and it implements the
    /// given version of the given interface.
    /// 
    /// </para>
    /// </summary>
    public event GlobalHandler? OnGlobal
    {
        add
        {
            _onGlobal += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onGlobal -= value;
        }
    }

    /// <summary>
    /// Announce removal of global object
    /// <para>
    ///
    /// Notify the client of removed global objects.
    ///
    /// This event notifies the client that the global identified
    /// by name is no longer available.  If the client bound to
    /// the global using the bind request, the client should now
    /// destroy that object.
    ///
    /// The object remains valid and requests to the object will be
    /// ignored until the client destroys it, to avoid races between
    /// the global going away and a client sending a request to it.
    /// 
    /// </para>
    /// </summary>
    public delegate void GlobalRemoveHandler(uint name);

    private GlobalRemoveHandler? _onGlobalRemove;

    /// <summary>
    /// Announce removal of global object
    /// <para>
    ///
    /// Notify the client of removed global objects.
    ///
    /// This event notifies the client that the global identified
    /// by name is no longer available.  If the client bound to
    /// the global using the bind request, the client should now
    /// destroy that object.
    ///
    /// The object remains valid and requests to the object will be
    /// ignored until the client destroys it, to avoid races between
    /// the global going away and a client sending a request to it.
    /// 
    /// </para>
    /// </summary>
    public event GlobalRemoveHandler? OnGlobalRemove
    {
        add
        {
            _onGlobalRemove += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onGlobalRemove -= value;
        }
    }

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to wl_registry");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (WlRegistry)handle.Target!;

            switch (opcode)
            {
                case 0: // global
                    if (obj._onGlobal != null)
                    {
                        var _name = args[0].u;
                        var __interface = Utf8StringMarshaller.ConvertToManaged(args[1].s) ?? string.Empty;
                        var _version = args[2].u;
                        obj._onGlobal?.Invoke(_name, __interface, _version);
                    }
                    break;
                case 1: // global_remove
                    if (obj._onGlobalRemove != null)
                    {
                        var _name = args[0].u;
                        obj._onGlobalRemove?.Invoke(_name);
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }
    /// <summary> Creates a WlRegistry wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new WlRegistry instance.</returns>
    public static WlRegistry Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new WlRegistry(handle, display);
    }
}
