// <auto-generated>
// This file was generated from wayland.xml
// Stability: Core
// Link: https://wayland.app/protocols/wayland
// </auto-generated>

#nullable enable

namespace WaylandDotnet;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// wl_shell
/// <para> create desktop-style surfaces </para>
/// <para> Version: 1 </para>
/// <see>https://wayland.app/protocols/wayland/#wl_shell</see>
/// </summary>
public sealed partial class WlShell : WaylandObject, IWaylandObjectFactory<WlShell>
{
    /// <summary> Wayland interface name for wl_shell. </summary>
    public const string InterfaceName = "wl_shell";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "wl_shell";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 1;

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing wl_shell proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public WlShell(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary>  </summary>
    public enum Error : uint
    {
        /// <summary>
        /// given wl_surface has another role
        /// </summary>
        Role = 0,
    }

    /// <summary>
    /// Create a shell surface from a surface
    /// <para>
    /// <br/>
    /// Create a shell surface for an existing surface. This gives<br/>
    /// the wl_surface the role of a shell surface. If the wl_surface<br/>
    /// already has another role, it raises a protocol error.<br/>
    /// <br/>
    /// Only one shell surface can be associated with a given surface.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe WlShellSurface GetShellSurface(WlSurface surface)
    {
        var args = stackalloc WlArgument[2];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].o = (WlObject*)(surface?.Handle ?? IntPtr.Zero);

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.WlShellSurface,
            (uint)WaylandInterfaces.WlShellSurface->Version,
            0,
            (nint)args
        );

        return new WlShellSurface(newProxy, Display);
    }

    /// <summary> Creates a WlShell wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new WlShell instance.</returns>
    public static WlShell Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new WlShell(handle, display);
    }
}
