// <auto-generated>
// This file was generated from wayland.xml
// Stability: Core
// Link: https://wayland.app/protocols/wayland
// </auto-generated>

#nullable enable

namespace WaylandDotnet;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// wl_shm_pool
/// <para> a shared memory pool </para>
/// <para> Version: 2 </para>
/// <see>https://wayland.app/protocols/wayland/#wl_shm_pool</see>
/// </summary>
public sealed partial class WlShmPool : WaylandObject, IWaylandObjectFactory<WlShmPool>
{
    /// <summary> Wayland interface name for wl_shm_pool. </summary>
    public const string InterfaceName = "wl_shm_pool";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "wl_shm_pool";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 2;

    private bool disposed;

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing wl_shm_pool proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public WlShmPool(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary>
    /// Create a buffer from the pool
    /// <para>
    /// <br/>
    /// Create a wl_buffer object from the pool.<br/>
    /// <br/>
    /// The buffer is created offset bytes into the pool and has<br/>
    /// width and height as specified.  The stride argument specifies<br/>
    /// the number of bytes from the beginning of one row to the beginning<br/>
    /// of the next.  The format is the pixel format of the buffer and<br/>
    /// must be one of those advertised through the wl_shm.format event.<br/>
    /// <br/>
    /// A buffer will keep a reference to the pool it was created from<br/>
    /// so it is valid to destroy the pool immediately after creating<br/>
    /// a buffer from it.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe WlBuffer CreateBuffer(int offset, int width, int height, int stride, uint format)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[6];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].i = offset;
        args[2].i = width;
        args[3].i = height;
        args[4].i = stride;
        args[5].u = format;

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.WlBuffer,
            (uint)WaylandInterfaces.WlBuffer->Version,
            0,
            (nint)args
        );

        return new WlBuffer(newProxy, Display);
    }

    /// <summary>
    /// Destroy the pool
    /// <para>
    /// <br/>
    /// Destroy the shared memory pool.<br/>
    /// <br/>
    /// The mmapped memory will be released when all<br/>
    /// buffers that have been created from this pool<br/>
    /// are gone.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary>
    /// Change the size of the pool mapping
    /// <para>
    /// <br/>
    /// This request will cause the server to remap the backing memory<br/>
    /// for the pool from the file descriptor passed when the pool was<br/>
    /// created, but using the new size.  This request can only be<br/>
    /// used to make the pool bigger.<br/>
    /// <br/>
    /// This request only changes the amount of bytes that are mmapped<br/>
    /// by the server and does not touch the file corresponding to the<br/>
    /// file descriptor passed at creation time. It is the client's<br/>
    /// responsibility to ensure that the file is at least as big as<br/>
    /// the new pool size.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Resize(int size)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].i = size;

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary> Creates a WlShmPool wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new WlShmPool instance.</returns>
    public static WlShmPool Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new WlShmPool(handle, display);
    }
}
