// <auto-generated>
// This file was generated from river-input-management-v1.xml
// Stability: River
// Link: https://wayland.app/protocols/river-input-management-v1
// </auto-generated>

#nullable enable

namespace WaylandDotnet.River;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// river_input_manager_v1
/// <para> input manager global interface </para>
/// <para> Version: 2 </para>
/// <see>https://wayland.app/protocols/river-input-management-v1/#river_input_manager_v1</see>
/// </summary>
public sealed partial class RiverInputManagerV1 : WaylandObject, IWaylandObjectFactory<RiverInputManagerV1>
{
    /// <summary> Wayland interface name for river_input_manager_v1. </summary>
    public const string InterfaceName = "river_input_manager_v1";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "river_input_manager_v1";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 2;

    private bool disposed;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing river_input_manager_v1 proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public RiverInputManagerV1(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary>  </summary>
    public enum Error : uint
    {
        /// <summary>
        ///
        /// </summary>
        InvalidDestroy = 0,
    }

    /// <summary>
    /// The server has finished with the input manager
    /// <para>
    ///
    /// This event indicates that the server will send no further events on this
    /// object. The client should destroy the object. See
    /// river_input_manager_v1.destroy for more information.
    /// 
    /// </para>
    /// </summary>
    public delegate void FinishedHandler();

    private FinishedHandler? _onFinished;

    /// <summary>
    /// The server has finished with the input manager
    /// <para>
    ///
    /// This event indicates that the server will send no further events on this
    /// object. The client should destroy the object. See
    /// river_input_manager_v1.destroy for more information.
    /// 
    /// </para>
    /// </summary>
    public event FinishedHandler? OnFinished
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onFinished += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onFinished -= value;
        }
    }

    /// <summary>
    /// New input device
    /// <para>
    ///
    /// A new input device has been created.
    /// 
    /// </para>
    /// </summary>
    public delegate void InputDeviceHandler(RiverInputDeviceV1 id);

    private InputDeviceHandler? _onInputDevice;

    /// <summary>
    /// New input device
    /// <para>
    ///
    /// A new input device has been created.
    /// 
    /// </para>
    /// </summary>
    public event InputDeviceHandler? OnInputDevice
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onInputDevice += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onInputDevice -= value;
        }
    }

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to river_input_manager_v1");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (RiverInputManagerV1)handle.Target!;

            switch (opcode)
            {
                case 0: // finished
                    if (obj._onFinished != null)
                    {
                        obj._onFinished?.Invoke();
                    }
                    break;
                case 1: // input_device
                    if (obj._onInputDevice != null)
                    {
                        if (args[0].o == (WlObject*)IntPtr.Zero) throw new InvalidOperationException("Received null object for non-nullable argument 'id'");
                        var _id = new RiverInputDeviceV1((IntPtr)args[0].o, obj.Display!);
                        obj._onInputDevice?.Invoke(_id);
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }
    /// <summary>
    /// Stop sending events
    /// <para>
    /// <br/>
    /// This request indicates that the client no longer wishes to receive<br/>
    /// events on this object.<br/>
    /// <br/>
    /// The Wayland protocol is asynchronous, which means the server may send<br/>
    /// further events until the stop request is processed. The client must wait<br/>
    /// for a river_input_manager_v1.finished event before destroying this<br/>
    /// object.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Stop()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Destroy the river_input_manager_v1 object
    /// <para>
    /// <br/>
    /// This request should be called after the finished event has been received<br/>
    /// to complete destruction of the object.<br/>
    /// <br/>
    /// It is a protocol error to make this request before the finished event<br/>
    /// has been received.<br/>
    /// <br/>
    /// If a client wishes to destroy this object it should send a<br/>
    /// river_input_manager_v1.stop request and wait for a<br/>
    /// river_input_manager_v1.finished event. Once the finished event is<br/>
    /// received it is safe to destroy this object and any other objects created<br/>
    /// through this interface.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary>
    /// Create a new seat
    /// <para>
    /// <br/>
    /// Create a new seat with the given name. Has no effect if a seat with the<br/>
    /// given name already exists.<br/>
    /// <br/>
    /// The default seat with name "default" always exists and does not need to<br/>
    /// be explicitly created.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void CreateSeat(string name)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].s = Utf8StringMarshaller.ConvertToUnmanaged(name);

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Destroy a seat
    /// <para>
    /// <br/>
    /// Destroy the seat with the given name. Has no effect if a seat with the<br/>
    /// given name does not exist.<br/>
    /// <br/>
    /// The default seat with name "default" cannot be destroyed and attempting<br/>
    /// to destroy it will have no effect.<br/>
    /// <br/>
    /// Any input devices assigned to the destroyed seat at the time of<br/>
    /// destruction are assigned to the default seat.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void DestroySeat(string name)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].s = Utf8StringMarshaller.ConvertToUnmanaged(name);

        const uint opcode = 3;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary> Creates a RiverInputManagerV1 wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new RiverInputManagerV1 instance.</returns>
    public static RiverInputManagerV1 Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new RiverInputManagerV1(handle, display);
    }
}
