// <auto-generated>
// This file was generated from ext-idle-notify-v1.xml
// Stability: Staging
// Link: https://wayland.app/protocols/ext-idle-notify-v1
// </auto-generated>

#nullable enable

namespace WaylandDotnet.Staging;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// ext_idle_notification_v1
/// <para> idle notification </para>
/// <para> Version: 2 </para>
/// <see>https://wayland.app/protocols/ext-idle-notify-v1/#ext_idle_notification_v1</see>
/// </summary>
public sealed partial class ExtIdleNotificationV1 : WaylandObject, IWaylandObjectFactory<ExtIdleNotificationV1>
{
    /// <summary> Wayland interface name for ext_idle_notification_v1. </summary>
    public const string InterfaceName = "ext_idle_notification_v1";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "ext_idle_notification_v1";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 2;

    private bool disposed;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing ext_idle_notification_v1 proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public ExtIdleNotificationV1(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary>
    /// Notification object is idle
    /// <para>
    ///
    /// This event is sent when the notification object becomes idle.
    ///
    /// It's a compositor protocol error to send this event twice without a
    /// resumed event in-between.
    /// 
    /// </para>
    /// </summary>
    public delegate void IdledHandler();

    private IdledHandler? _onIdled;

    /// <summary>
    /// Notification object is idle
    /// <para>
    ///
    /// This event is sent when the notification object becomes idle.
    ///
    /// It's a compositor protocol error to send this event twice without a
    /// resumed event in-between.
    /// 
    /// </para>
    /// </summary>
    public event IdledHandler? OnIdled
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onIdled += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onIdled -= value;
        }
    }

    /// <summary>
    /// Notification object is no longer idle
    /// <para>
    ///
    /// This event is sent when the notification object stops being idle.
    ///
    /// It's a compositor protocol error to send this event twice without an
    /// idled event in-between. It's a compositor protocol error to send this
    /// event prior to any idled event.
    /// 
    /// </para>
    /// </summary>
    public delegate void ResumedHandler();

    private ResumedHandler? _onResumed;

    /// <summary>
    /// Notification object is no longer idle
    /// <para>
    ///
    /// This event is sent when the notification object stops being idle.
    ///
    /// It's a compositor protocol error to send this event twice without an
    /// idled event in-between. It's a compositor protocol error to send this
    /// event prior to any idled event.
    /// 
    /// </para>
    /// </summary>
    public event ResumedHandler? OnResumed
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onResumed += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onResumed -= value;
        }
    }

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to ext_idle_notification_v1");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (ExtIdleNotificationV1)handle.Target!;

            switch (opcode)
            {
                case 0: // idled
                    if (obj._onIdled != null)
                    {
                        obj._onIdled?.Invoke();
                    }
                    break;
                case 1: // resumed
                    if (obj._onResumed != null)
                    {
                        obj._onResumed?.Invoke();
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }
    /// <summary>
    /// Destroy the notification object
    /// <para>
    /// <br/>
    /// Destroy the notification object.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary> Creates a ExtIdleNotificationV1 wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new ExtIdleNotificationV1 instance.</returns>
    public static ExtIdleNotificationV1 Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new ExtIdleNotificationV1(handle, display);
    }
}
