// <auto-generated>
// This file was generated from tablet-v2.xml
// Stability: Stable
// Link: https://wayland.app/protocols/tablet-v2
// </auto-generated>

#nullable enable

namespace WaylandDotnet.Stable;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// zwp_tablet_v2
/// <para> graphics tablet device </para>
/// <para> Version: 2 </para>
/// <see>https://wayland.app/protocols/tablet-v2/#zwp_tablet_v2</see>
/// </summary>
public sealed partial class ZwpTabletV2 : WaylandObject, IWaylandObjectFactory<ZwpTabletV2>
{
    /// <summary> Wayland interface name for zwp_tablet_v2. </summary>
    public const string InterfaceName = "zwp_tablet_v2";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "zwp_tablet_v2";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 2;

    private bool disposed;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing zwp_tablet_v2 proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public ZwpTabletV2(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary> bus type  </summary>
    public enum Bustype : uint
    {
        /// <summary>
        /// USB
        /// </summary>
        Usb = 3,
        /// <summary>
        /// Bluetooth
        /// </summary>
        Bluetooth = 5,
        /// <summary>
        /// Virtual
        /// </summary>
        Virtual = 6,
        /// <summary>
        /// Serial
        /// </summary>
        Serial = 17,
        /// <summary>
        /// I2C
        /// </summary>
        I2c = 24,
    }

    /// <summary>
    /// Tablet device name
    /// <para>
    ///
    /// A descriptive name for the tablet device.
    ///
    /// If the device has no descriptive name, this event is not sent.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    /// 
    /// </para>
    /// </summary>
    public delegate void NameHandler(string name);

    private NameHandler? _onName;

    /// <summary>
    /// Tablet device name
    /// <para>
    ///
    /// A descriptive name for the tablet device.
    ///
    /// If the device has no descriptive name, this event is not sent.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    /// 
    /// </para>
    /// </summary>
    public event NameHandler? OnName
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onName += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onName -= value;
        }
    }

    /// <summary>
    /// Tablet device vendor/product id
    /// <para>
    ///
    /// The vendor and product IDs for the tablet device.
    ///
    /// The interpretation of the id depends on the zwp_tablet_v2.bustype.
    /// Prior to version v2 of this protocol, the id was implied to be a USB
    /// vendor and product ID. If no zwp_tablet_v2.bustype is sent, the ID
    /// is to be interpreted as USB vendor and product ID.
    ///
    /// If the device has no vendor/product ID, this event is not sent.
    /// This can happen for virtual devices or non-USB devices, for instance.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    /// 
    /// </para>
    /// </summary>
    public delegate void IdHandler(uint vid, uint pid);

    private IdHandler? _onId;

    /// <summary>
    /// Tablet device vendor/product id
    /// <para>
    ///
    /// The vendor and product IDs for the tablet device.
    ///
    /// The interpretation of the id depends on the zwp_tablet_v2.bustype.
    /// Prior to version v2 of this protocol, the id was implied to be a USB
    /// vendor and product ID. If no zwp_tablet_v2.bustype is sent, the ID
    /// is to be interpreted as USB vendor and product ID.
    ///
    /// If the device has no vendor/product ID, this event is not sent.
    /// This can happen for virtual devices or non-USB devices, for instance.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    /// 
    /// </para>
    /// </summary>
    public event IdHandler? OnId
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onId += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onId -= value;
        }
    }

    /// <summary>
    /// Path to the device
    /// <para>
    ///
    /// A system-specific device path that indicates which device is behind
    /// this zwp_tablet_v2. This information may be used to gather additional
    /// information about the device, e.g. through libwacom.
    ///
    /// A device may have more than one device path. If so, multiple
    /// zwp_tablet_v2.path events are sent. A device may be emulated and not
    /// have a device path, and in that case this event will not be sent.
    ///
    /// The format of the path is unspecified, it may be a device node, a
    /// sysfs path, or some other identifier. It is up to the client to
    /// identify the string provided.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    /// 
    /// </para>
    /// </summary>
    public delegate void PathHandler(string path);

    private PathHandler? _onPath;

    /// <summary>
    /// Path to the device
    /// <para>
    ///
    /// A system-specific device path that indicates which device is behind
    /// this zwp_tablet_v2. This information may be used to gather additional
    /// information about the device, e.g. through libwacom.
    ///
    /// A device may have more than one device path. If so, multiple
    /// zwp_tablet_v2.path events are sent. A device may be emulated and not
    /// have a device path, and in that case this event will not be sent.
    ///
    /// The format of the path is unspecified, it may be a device node, a
    /// sysfs path, or some other identifier. It is up to the client to
    /// identify the string provided.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    /// 
    /// </para>
    /// </summary>
    public event PathHandler? OnPath
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onPath += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onPath -= value;
        }
    }

    /// <summary>
    /// Tablet description events sequence complete
    /// <para>
    ///
    /// This event is sent immediately to signal the end of the initial
    /// burst of descriptive events. A client may consider the static
    /// description of the tablet to be complete and finalize initialization
    /// of the tablet.
    /// 
    /// </para>
    /// </summary>
    public delegate void DoneHandler();

    private DoneHandler? _onDone;

    /// <summary>
    /// Tablet description events sequence complete
    /// <para>
    ///
    /// This event is sent immediately to signal the end of the initial
    /// burst of descriptive events. A client may consider the static
    /// description of the tablet to be complete and finalize initialization
    /// of the tablet.
    /// 
    /// </para>
    /// </summary>
    public event DoneHandler? OnDone
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onDone += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onDone -= value;
        }
    }

    /// <summary>
    /// Tablet removed event
    /// <para>
    ///
    /// Sent when the tablet has been removed from the system. When a tablet
    /// is removed, some tools may be removed.
    ///
    /// When this event is received, the client must zwp_tablet_v2.destroy
    /// the object.
    /// 
    /// </para>
    /// </summary>
    public delegate void RemovedHandler();

    private RemovedHandler? _onRemoved;

    /// <summary>
    /// Tablet removed event
    /// <para>
    ///
    /// Sent when the tablet has been removed from the system. When a tablet
    /// is removed, some tools may be removed.
    ///
    /// When this event is received, the client must zwp_tablet_v2.destroy
    /// the object.
    /// 
    /// </para>
    /// </summary>
    public event RemovedHandler? OnRemoved
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onRemoved += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onRemoved -= value;
        }
    }

    /// <summary>
    /// Tablet device bus type
    /// <para>
    ///
    /// The bustype argument is one of the BUS_ defines in the Linux kernel's
    /// linux/input.h
    ///
    /// If the device has no known bustype or the bustype cannot be
    /// queried, this event is not sent.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    /// 
    /// </para>
    /// </summary>
    public delegate void BustypeHandler(uint bustype);

    private BustypeHandler? _onBustype;

    /// <summary>
    /// Tablet device bus type
    /// <para>
    ///
    /// The bustype argument is one of the BUS_ defines in the Linux kernel's
    /// linux/input.h
    ///
    /// If the device has no known bustype or the bustype cannot be
    /// queried, this event is not sent.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    /// 
    /// </para>
    /// </summary>
    public event BustypeHandler? OnBustype
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onBustype += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onBustype -= value;
        }
    }

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to zwp_tablet_v2");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (ZwpTabletV2)handle.Target!;

            switch (opcode)
            {
                case 0: // name
                    if (obj._onName != null)
                    {
                        var _name = Utf8StringMarshaller.ConvertToManaged(args[0].s) ?? string.Empty;
                        obj._onName?.Invoke(_name);
                    }
                    break;
                case 1: // id
                    if (obj._onId != null)
                    {
                        var _vid = args[0].u;
                        var _pid = args[1].u;
                        obj._onId?.Invoke(_vid, _pid);
                    }
                    break;
                case 2: // path
                    if (obj._onPath != null)
                    {
                        var _path = Utf8StringMarshaller.ConvertToManaged(args[0].s) ?? string.Empty;
                        obj._onPath?.Invoke(_path);
                    }
                    break;
                case 3: // done
                    if (obj._onDone != null)
                    {
                        obj._onDone?.Invoke();
                    }
                    break;
                case 4: // removed
                    if (obj._onRemoved != null)
                    {
                        obj._onRemoved?.Invoke();
                    }
                    break;
                case 5: // bustype
                    if (obj._onBustype != null)
                    {
                        var _bustype = args[0].u;
                        obj._onBustype?.Invoke(_bustype);
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }
    /// <summary>
    /// Destroy the tablet object
    /// <para>
    /// <br/>
    /// This destroys the client's resource for this tablet object.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary> Creates a ZwpTabletV2 wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new ZwpTabletV2 instance.</returns>
    public static ZwpTabletV2 Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new ZwpTabletV2(handle, display);
    }
}
