// <auto-generated>
// This file was generated from tablet-v2.xml
// Stability: Stable
// Link: https://wayland.app/protocols/tablet-v2
// </auto-generated>

#nullable enable

namespace WaylandDotnet.Stable;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// zwp_tablet_seat_v2
/// <para> controller object for graphic tablet devices of a seat </para>
/// <para> Version: 2 </para>
/// <see>https://wayland.app/protocols/tablet-v2/#zwp_tablet_seat_v2</see>
/// </summary>
public sealed partial class ZwpTabletSeatV2 : WaylandObject, IWaylandObjectFactory<ZwpTabletSeatV2>
{
    /// <summary> Wayland interface name for zwp_tablet_seat_v2. </summary>
    public const string InterfaceName = "zwp_tablet_seat_v2";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "zwp_tablet_seat_v2";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 2;

    private bool disposed;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing zwp_tablet_seat_v2 proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public ZwpTabletSeatV2(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary>
    /// New device notification
    /// <para>
    ///
    /// This event is sent whenever a new tablet becomes available on this
    /// seat. This event only provides the object id of the tablet, any
    /// static information about the tablet (device name, vid/pid, etc.) is
    /// sent through the zwp_tablet_v2 interface.
    /// 
    /// </para>
    /// </summary>
    public delegate void TabletAddedHandler(ZwpTabletV2 id);

    private TabletAddedHandler? _onTabletAdded;

    /// <summary>
    /// New device notification
    /// <para>
    ///
    /// This event is sent whenever a new tablet becomes available on this
    /// seat. This event only provides the object id of the tablet, any
    /// static information about the tablet (device name, vid/pid, etc.) is
    /// sent through the zwp_tablet_v2 interface.
    /// 
    /// </para>
    /// </summary>
    public event TabletAddedHandler? OnTabletAdded
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onTabletAdded += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onTabletAdded -= value;
        }
    }

    /// <summary>
    /// A new tool has been used with a tablet
    /// <para>
    ///
    /// This event is sent whenever a tool that has not previously been used
    /// with a tablet comes into use. This event only provides the object id
    /// of the tool; any static information about the tool (capabilities,
    /// type, etc.) is sent through the zwp_tablet_tool_v2 interface.
    /// 
    /// </para>
    /// </summary>
    public delegate void ToolAddedHandler(ZwpTabletToolV2 id);

    private ToolAddedHandler? _onToolAdded;

    /// <summary>
    /// A new tool has been used with a tablet
    /// <para>
    ///
    /// This event is sent whenever a tool that has not previously been used
    /// with a tablet comes into use. This event only provides the object id
    /// of the tool; any static information about the tool (capabilities,
    /// type, etc.) is sent through the zwp_tablet_tool_v2 interface.
    /// 
    /// </para>
    /// </summary>
    public event ToolAddedHandler? OnToolAdded
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onToolAdded += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onToolAdded -= value;
        }
    }

    /// <summary>
    /// New pad notification
    /// <para>
    ///
    /// This event is sent whenever a new pad is known to the system. Typically,
    /// pads are physically attached to tablets and a pad_added event is
    /// sent immediately after the zwp_tablet_seat_v2.tablet_added.
    /// However, some standalone pad devices logically attach to tablets at
    /// runtime, and the client must wait for zwp_tablet_pad_v2.enter to know
    /// the tablet a pad is attached to.
    ///
    /// This event only provides the object id of the pad. All further
    /// features (buttons, strips, rings) are sent through the zwp_tablet_pad_v2
    /// interface.
    /// 
    /// </para>
    /// </summary>
    public delegate void PadAddedHandler(ZwpTabletPadV2 id);

    private PadAddedHandler? _onPadAdded;

    /// <summary>
    /// New pad notification
    /// <para>
    ///
    /// This event is sent whenever a new pad is known to the system. Typically,
    /// pads are physically attached to tablets and a pad_added event is
    /// sent immediately after the zwp_tablet_seat_v2.tablet_added.
    /// However, some standalone pad devices logically attach to tablets at
    /// runtime, and the client must wait for zwp_tablet_pad_v2.enter to know
    /// the tablet a pad is attached to.
    ///
    /// This event only provides the object id of the pad. All further
    /// features (buttons, strips, rings) are sent through the zwp_tablet_pad_v2
    /// interface.
    /// 
    /// </para>
    /// </summary>
    public event PadAddedHandler? OnPadAdded
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onPadAdded += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onPadAdded -= value;
        }
    }

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to zwp_tablet_seat_v2");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (ZwpTabletSeatV2)handle.Target!;

            switch (opcode)
            {
                case 0: // tablet_added
                    if (obj._onTabletAdded != null)
                    {
                        if (args[0].o == (WlObject*)IntPtr.Zero) throw new InvalidOperationException("Received null object for non-nullable argument 'id'");
                        var _id = new ZwpTabletV2((IntPtr)args[0].o, obj.Display!);
                        obj._onTabletAdded?.Invoke(_id);
                    }
                    break;
                case 1: // tool_added
                    if (obj._onToolAdded != null)
                    {
                        if (args[0].o == (WlObject*)IntPtr.Zero) throw new InvalidOperationException("Received null object for non-nullable argument 'id'");
                        var _id = new ZwpTabletToolV2((IntPtr)args[0].o, obj.Display!);
                        obj._onToolAdded?.Invoke(_id);
                    }
                    break;
                case 2: // pad_added
                    if (obj._onPadAdded != null)
                    {
                        if (args[0].o == (WlObject*)IntPtr.Zero) throw new InvalidOperationException("Received null object for non-nullable argument 'id'");
                        var _id = new ZwpTabletPadV2((IntPtr)args[0].o, obj.Display!);
                        obj._onPadAdded?.Invoke(_id);
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }
    /// <summary>
    /// Release the memory for the tablet seat object
    /// <para>
    /// <br/>
    /// Destroy the zwp_tablet_seat_v2 object. Objects created from this<br/>
    /// object are unaffected and should be destroyed separately.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary> Creates a ZwpTabletSeatV2 wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new ZwpTabletSeatV2 instance.</returns>
    public static ZwpTabletSeatV2 Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new ZwpTabletSeatV2(handle, display);
    }
}
