// <auto-generated>
// This file was generated from ext-workspace-v1.xml
// Stability: Staging
// Link: https://wayland.app/protocols/ext-workspace-v1
// </auto-generated>

#nullable enable

namespace WaylandDotnet.Staging;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// ext_workspace_handle_v1
/// <para> a workspace handing a group of surfaces </para>
/// <para> Version: 1 </para>
/// <see>https://wayland.app/protocols/ext-workspace-v1/#ext_workspace_handle_v1</see>
/// </summary>
public sealed partial class ExtWorkspaceHandleV1 : WaylandObject, IWaylandObjectFactory<ExtWorkspaceHandleV1>
{
    /// <summary> Wayland interface name for ext_workspace_handle_v1. </summary>
    public const string InterfaceName = "ext_workspace_handle_v1";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "ext_workspace_handle_v1";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 1;

    private bool disposed;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing ext_workspace_handle_v1 proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public ExtWorkspaceHandleV1(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary> types of states on the workspace </summary>
    [Flags]
    public enum StateFlag : uint
    {
        /// <summary>
        /// the workspace is active
        /// </summary>
        Active = 1,
        /// <summary>
        /// the workspace requests attention
        /// </summary>
        Urgent = 2,
        /// <summary>
        ///
        /// </summary>
        Hidden = 4,
    }

    /// <summary>  </summary>
    [Flags]
    public enum WorkspaceCapabilitiesFlag : uint
    {
        /// <summary>
        /// activate request is available
        /// </summary>
        Activate = 1,
        /// <summary>
        /// deactivate request is available
        /// </summary>
        Deactivate = 2,
        /// <summary>
        /// remove request is available
        /// </summary>
        Remove = 4,
        /// <summary>
        /// assign request is available
        /// </summary>
        Assign = 8,
    }

    /// <summary>
    /// Workspace id
    /// <para>
    ///
    /// If this event is emitted, it will be send immediately after the
    /// ext_workspace_handle_v1 is created or when an id is assigned to
    /// a workspace (at most once during its lifetime).
    ///
    /// An id will never change during the lifetime of the `ext_workspace_handle_v1`
    /// and is guaranteed to be unique during its lifetime.
    ///
    /// Ids are not human-readable and shouldn't be displayed, use `name` for that purpose.
    ///
    /// Compositors are expected to only send ids for workspaces likely stable across multiple
    /// sessions and can be used by clients to store preferences for workspaces. Workspaces without
    /// ids should be considered temporary and any data associated with them should be deleted once
    /// the respective object is lost.
    /// 
    /// </para>
    /// </summary>
    public delegate void IdHandler(string id);

    private IdHandler? _onId;

    /// <summary>
    /// Workspace id
    /// <para>
    ///
    /// If this event is emitted, it will be send immediately after the
    /// ext_workspace_handle_v1 is created or when an id is assigned to
    /// a workspace (at most once during its lifetime).
    ///
    /// An id will never change during the lifetime of the `ext_workspace_handle_v1`
    /// and is guaranteed to be unique during its lifetime.
    ///
    /// Ids are not human-readable and shouldn't be displayed, use `name` for that purpose.
    ///
    /// Compositors are expected to only send ids for workspaces likely stable across multiple
    /// sessions and can be used by clients to store preferences for workspaces. Workspaces without
    /// ids should be considered temporary and any data associated with them should be deleted once
    /// the respective object is lost.
    /// 
    /// </para>
    /// </summary>
    public event IdHandler? OnId
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onId += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onId -= value;
        }
    }

    /// <summary>
    /// Workspace name changed
    /// <para>
    ///
    /// This event is emitted immediately after the ext_workspace_handle_v1 is
    /// created and whenever the name of the workspace changes.
    ///
    /// A name is meant to be human-readable and can be displayed to a user.
    /// Unlike the id it is neither stable nor unique.
    /// 
    /// </para>
    /// </summary>
    public delegate void NameHandler(string name);

    private NameHandler? _onName;

    /// <summary>
    /// Workspace name changed
    /// <para>
    ///
    /// This event is emitted immediately after the ext_workspace_handle_v1 is
    /// created and whenever the name of the workspace changes.
    ///
    /// A name is meant to be human-readable and can be displayed to a user.
    /// Unlike the id it is neither stable nor unique.
    /// 
    /// </para>
    /// </summary>
    public event NameHandler? OnName
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onName += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onName -= value;
        }
    }

    /// <summary>
    /// Workspace coordinates changed
    /// <para>
    ///
    /// This event is used to organize workspaces into an N-dimensional grid
    /// within a workspace group, and if supported, is emitted immediately after
    /// the ext_workspace_handle_v1 is created and whenever the coordinates of
    /// the workspace change. Compositors may not send this event if they do not
    /// conceptually arrange workspaces in this way. If compositors simply
    /// number workspaces, without any geometric interpretation, they may send
    /// 1D coordinates, which clients should not interpret as implying any
    /// geometry. Sending an empty array means that the compositor no longer
    /// orders the workspace geometrically.
    ///
    /// Coordinates have an arbitrary number of dimensions N with an uint32
    /// position along each dimension. By convention if N > 1, the first
    /// dimension is X, the second Y, the third Z, and so on. The compositor may
    /// chose to utilize these events for a more novel workspace layout
    /// convention, however. No guarantee is made about the grid being filled or
    /// bounded; there may be a workspace at coordinate 1 and another at
    /// coordinate 1000 and none in between. Within a workspace group, however,
    /// workspaces must have unique coordinates of equal dimensionality.
    /// 
    /// </para>
    /// </summary>
    public delegate void CoordinatesHandler(byte[] coordinates);

    private CoordinatesHandler? _onCoordinates;

    /// <summary>
    /// Workspace coordinates changed
    /// <para>
    ///
    /// This event is used to organize workspaces into an N-dimensional grid
    /// within a workspace group, and if supported, is emitted immediately after
    /// the ext_workspace_handle_v1 is created and whenever the coordinates of
    /// the workspace change. Compositors may not send this event if they do not
    /// conceptually arrange workspaces in this way. If compositors simply
    /// number workspaces, without any geometric interpretation, they may send
    /// 1D coordinates, which clients should not interpret as implying any
    /// geometry. Sending an empty array means that the compositor no longer
    /// orders the workspace geometrically.
    ///
    /// Coordinates have an arbitrary number of dimensions N with an uint32
    /// position along each dimension. By convention if N > 1, the first
    /// dimension is X, the second Y, the third Z, and so on. The compositor may
    /// chose to utilize these events for a more novel workspace layout
    /// convention, however. No guarantee is made about the grid being filled or
    /// bounded; there may be a workspace at coordinate 1 and another at
    /// coordinate 1000 and none in between. Within a workspace group, however,
    /// workspaces must have unique coordinates of equal dimensionality.
    /// 
    /// </para>
    /// </summary>
    public event CoordinatesHandler? OnCoordinates
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onCoordinates += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onCoordinates -= value;
        }
    }

    /// <summary>
    /// The state of the workspace changed
    /// <para>
    ///
    /// This event is emitted immediately after the ext_workspace_handle_v1 is
    /// created and each time the workspace state changes, either because of a
    /// compositor action or because of a request in this protocol.
    ///
    /// Missing states convey the opposite meaning, e.g. an unset active bit
    /// means the workspace is currently inactive.
    /// 
    /// </para>
    /// </summary>
    public delegate void StateHandler(uint state);

    private StateHandler? _onState;

    /// <summary>
    /// The state of the workspace changed
    /// <para>
    ///
    /// This event is emitted immediately after the ext_workspace_handle_v1 is
    /// created and each time the workspace state changes, either because of a
    /// compositor action or because of a request in this protocol.
    ///
    /// Missing states convey the opposite meaning, e.g. an unset active bit
    /// means the workspace is currently inactive.
    /// 
    /// </para>
    /// </summary>
    public event StateHandler? OnState
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onState += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onState -= value;
        }
    }

    /// <summary>
    /// Compositor capabilities
    /// <para>
    ///
    /// This event advertises the capabilities supported by the compositor. If
    /// a capability isn't supported, clients should hide or disable the UI
    /// elements that expose this functionality. For instance, if the
    /// compositor doesn't advertise support for removing workspaces, a button
    /// triggering the remove request should not be displayed.
    ///
    /// The compositor will ignore requests it doesn't support. For instance,
    /// a compositor which doesn't advertise support for remove will ignore
    /// remove requests.
    ///
    /// Compositors must send this event once after creation of an
    /// ext_workspace_handle_v1 . When the capabilities change, compositors
    /// must send this event again.
    /// 
    /// </para>
    /// </summary>
    public delegate void CapabilitiesHandler(uint capabilities);

    private CapabilitiesHandler? _onCapabilities;

    /// <summary>
    /// Compositor capabilities
    /// <para>
    ///
    /// This event advertises the capabilities supported by the compositor. If
    /// a capability isn't supported, clients should hide or disable the UI
    /// elements that expose this functionality. For instance, if the
    /// compositor doesn't advertise support for removing workspaces, a button
    /// triggering the remove request should not be displayed.
    ///
    /// The compositor will ignore requests it doesn't support. For instance,
    /// a compositor which doesn't advertise support for remove will ignore
    /// remove requests.
    ///
    /// Compositors must send this event once after creation of an
    /// ext_workspace_handle_v1 . When the capabilities change, compositors
    /// must send this event again.
    /// 
    /// </para>
    /// </summary>
    public event CapabilitiesHandler? OnCapabilities
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onCapabilities += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onCapabilities -= value;
        }
    }

    /// <summary>
    /// This workspace has been removed
    /// <para>
    ///
    /// This event is send when the workspace associated with the ext_workspace_handle_v1
    /// has been removed. After sending this request, the compositor will immediately consider
    /// the object inert. Any requests will be ignored except the destroy request.
    ///
    /// It is guaranteed there won't be any more events referencing this
    /// ext_workspace_handle_v1.
    ///
    /// The compositor must only remove a workspaces not currently belonging to any
    /// workspace_group.
    /// 
    /// </para>
    /// </summary>
    public delegate void RemovedHandler();

    private RemovedHandler? _onRemoved;

    /// <summary>
    /// This workspace has been removed
    /// <para>
    ///
    /// This event is send when the workspace associated with the ext_workspace_handle_v1
    /// has been removed. After sending this request, the compositor will immediately consider
    /// the object inert. Any requests will be ignored except the destroy request.
    ///
    /// It is guaranteed there won't be any more events referencing this
    /// ext_workspace_handle_v1.
    ///
    /// The compositor must only remove a workspaces not currently belonging to any
    /// workspace_group.
    /// 
    /// </para>
    /// </summary>
    public event RemovedHandler? OnRemoved
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onRemoved += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onRemoved -= value;
        }
    }

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to ext_workspace_handle_v1");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (ExtWorkspaceHandleV1)handle.Target!;

            switch (opcode)
            {
                case 0: // id
                    if (obj._onId != null)
                    {
                        var _id = Utf8StringMarshaller.ConvertToManaged(args[0].s) ?? string.Empty;
                        obj._onId?.Invoke(_id);
                    }
                    break;
                case 1: // name
                    if (obj._onName != null)
                    {
                        var _name = Utf8StringMarshaller.ConvertToManaged(args[0].s) ?? string.Empty;
                        obj._onName?.Invoke(_name);
                    }
                    break;
                case 2: // coordinates
                    if (obj._onCoordinates != null)
                    {
                        var _coordinates = args[0].a;
                        obj._onCoordinates?.Invoke(WaylandMarshal.ToSpan(_coordinates));
                    }
                    break;
                case 3: // state
                    if (obj._onState != null)
                    {
                        var _state = args[0].u;
                        obj._onState?.Invoke(_state);
                    }
                    break;
                case 4: // capabilities
                    if (obj._onCapabilities != null)
                    {
                        var _capabilities = args[0].u;
                        obj._onCapabilities?.Invoke(_capabilities);
                    }
                    break;
                case 5: // removed
                    if (obj._onRemoved != null)
                    {
                        obj._onRemoved?.Invoke();
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }
    /// <summary>
    /// Destroy the ext_workspace_handle_v1 object
    /// <para>
    /// <br/>
    /// Destroys the ext_workspace_handle_v1 object.<br/>
    /// <br/>
    /// This request should be made either when the client does not want to<br/>
    /// use the workspace object any more or after the remove event to finalize<br/>
    /// the destruction of the object.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary>
    /// Activate the workspace
    /// <para>
    /// <br/>
    /// Request that this workspace be activated.<br/>
    /// <br/>
    /// There is no guarantee the workspace will be actually activated, and<br/>
    /// behaviour may be compositor-dependent. For example, activating a<br/>
    /// workspace may or may not deactivate all other workspaces in the same<br/>
    /// group.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Activate()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Deactivate the workspace
    /// <para>
    /// <br/>
    /// Request that this workspace be deactivated.<br/>
    /// <br/>
    /// There is no guarantee the workspace will be actually deactivated.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Deactivate()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Assign workspace to group
    /// <para>
    /// <br/>
    /// Requests that this workspace is assigned to the given workspace group.<br/>
    /// <br/>
    /// There is no guarantee the workspace will be assigned.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Assign(ExtWorkspaceGroupHandleV1 workspaceGroup)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].o = (WlObject*)(workspaceGroup?.Handle ?? IntPtr.Zero);

        const uint opcode = 3;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Remove the workspace
    /// <para>
    /// <br/>
    /// Request that this workspace be removed.<br/>
    /// <br/>
    /// There is no guarantee the workspace will be actually removed.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Remove()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 4;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary> Creates a ExtWorkspaceHandleV1 wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new ExtWorkspaceHandleV1 instance.</returns>
    public static ExtWorkspaceHandleV1 Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new ExtWorkspaceHandleV1(handle, display);
    }
}
