// <auto-generated>
// This file was generated from xdg-shell.xml
// Stability: Stable
// Link: https://wayland.app/protocols/xdg-shell
// </auto-generated>

#nullable enable

namespace WaylandDotnet.Stable;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// xdg_positioner
/// <para> child surface positioner </para>
/// <para> Version: 7 </para>
/// <see>https://wayland.app/protocols/xdg-shell/#xdg_positioner</see>
/// </summary>
public sealed partial class XdgPositioner : WaylandObject, IWaylandObjectFactory<XdgPositioner>
{
    /// <summary> Wayland interface name for xdg_positioner. </summary>
    public const string InterfaceName = "xdg_positioner";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "xdg_positioner";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 7;

    private bool disposed;

    /// <summary>
    /// Wraps an existing xdg_positioner proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    public XdgPositioner(IntPtr handle)
    {
        Handle = handle;
    }
    /// <summary>  </summary>
    public enum Error : uint
    {
        /// <summary>
        /// invalid input provided
        /// </summary>
        InvalidInput = 0,
    }

    /// <summary>  </summary>
    public enum Anchor : uint
    {
        /// <summary>
        ///
        /// </summary>
        None = 0,
        /// <summary>
        ///
        /// </summary>
        Top = 1,
        /// <summary>
        ///
        /// </summary>
        Bottom = 2,
        /// <summary>
        ///
        /// </summary>
        Left = 3,
        /// <summary>
        ///
        /// </summary>
        Right = 4,
        /// <summary>
        ///
        /// </summary>
        TopLeft = 5,
        /// <summary>
        ///
        /// </summary>
        BottomLeft = 6,
        /// <summary>
        ///
        /// </summary>
        TopRight = 7,
        /// <summary>
        ///
        /// </summary>
        BottomRight = 8,
    }

    /// <summary>  </summary>
    public enum Gravity : uint
    {
        /// <summary>
        ///
        /// </summary>
        None = 0,
        /// <summary>
        ///
        /// </summary>
        Top = 1,
        /// <summary>
        ///
        /// </summary>
        Bottom = 2,
        /// <summary>
        ///
        /// </summary>
        Left = 3,
        /// <summary>
        ///
        /// </summary>
        Right = 4,
        /// <summary>
        ///
        /// </summary>
        TopLeft = 5,
        /// <summary>
        ///
        /// </summary>
        BottomLeft = 6,
        /// <summary>
        ///
        /// </summary>
        TopRight = 7,
        /// <summary>
        ///
        /// </summary>
        BottomRight = 8,
    }

    /// <summary> constraint adjustments </summary>
    [Flags]
    public enum ConstraintAdjustmentFlag : uint
    {
        /// <summary>
        ///
        /// </summary>
        None = 0,
        /// <summary>
        ///
        /// </summary>
        SlideX = 1,
        /// <summary>
        ///
        /// </summary>
        SlideY = 2,
        /// <summary>
        ///
        /// </summary>
        FlipX = 4,
        /// <summary>
        ///
        /// </summary>
        FlipY = 8,
        /// <summary>
        ///
        /// </summary>
        ResizeX = 16,
        /// <summary>
        ///
        /// </summary>
        ResizeY = 32,
    }

    /// <summary>
    /// Destroy the xdg_positioner object
    /// <para>
    /// <br/>
    /// Notify the compositor that the xdg_positioner will no longer be used.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary>
    /// Set the size of the to-be positioned rectangle
    /// <para>
    /// <br/>
    /// Set the size of the surface that is to be positioned with the positioner<br/>
    /// object. The size is in surface-local coordinates and corresponds to the<br/>
    /// window geometry. See xdg_surface.set_window_geometry.<br/>
    /// <br/>
    /// If a zero or negative size is set the invalid_input error is raised.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetSize(int width, int height)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[2];
        args[0].i = width;
        args[1].i = height;

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set the anchor rectangle within the parent surface
    /// <para>
    /// <br/>
    /// Specify the anchor rectangle within the parent surface that the child<br/>
    /// surface will be placed relative to. The rectangle is relative to the<br/>
    /// window geometry as defined by xdg_surface.set_window_geometry of the<br/>
    /// parent surface.<br/>
    /// <br/>
    /// When the xdg_positioner object is used to position a child surface, the<br/>
    /// anchor rectangle may not extend outside the window geometry of the<br/>
    /// positioned child's parent surface.<br/>
    /// <br/>
    /// If a negative size is set the invalid_input error is raised.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetAnchorRect(int x, int y, int width, int height)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[4];
        args[0].i = x;
        args[1].i = y;
        args[2].i = width;
        args[3].i = height;

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set anchor rectangle anchor
    /// <para>
    /// <br/>
    /// Defines the anchor point for the anchor rectangle. The specified anchor<br/>
    /// is used to derive an anchor point that the child surface will be<br/>
    /// positioned relative to. If a corner anchor is set (e.g. 'top_left' or<br/>
    /// 'bottom_right'), the anchor point will be at the specified corner;<br/>
    /// otherwise, the derived anchor point will be centered on the specified<br/>
    /// edge, or in the center of the anchor rectangle if no edge is specified.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetAnchor(uint anchor)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].u = anchor;

        const uint opcode = 3;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set child surface gravity
    /// <para>
    /// <br/>
    /// Defines in what direction a surface should be positioned, relative to<br/>
    /// the anchor point of the parent surface. If a corner gravity is<br/>
    /// specified (e.g. 'bottom_right' or 'top_left'), then the child surface<br/>
    /// will be placed towards the specified gravity; otherwise, the child<br/>
    /// surface will be centered over the anchor point on any axis that had no<br/>
    /// gravity specified. If the gravity is not in the ‘gravity’ enum, an<br/>
    /// invalid_input error is raised.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetGravity(uint gravity)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].u = gravity;

        const uint opcode = 4;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set the adjustment to be done when constrained
    /// <para>
    /// <br/>
    /// Specify how the window should be positioned if the originally intended<br/>
    /// position caused the surface to be constrained, meaning at least<br/>
    /// partially outside positioning boundaries set by the compositor. The<br/>
    /// adjustment is set by constructing a bitmask describing the adjustment to<br/>
    /// be made when the surface is constrained on that axis.<br/>
    /// <br/>
    /// If no bit for one axis is set, the compositor will assume that the child<br/>
    /// surface should not change its position on that axis when constrained.<br/>
    /// <br/>
    /// If more than one bit for one axis is set, the order of how adjustments<br/>
    /// are applied is specified in the corresponding adjustment descriptions.<br/>
    /// <br/>
    /// The default adjustment is none.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetConstraintAdjustment(uint constraintAdjustment)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].u = constraintAdjustment;

        const uint opcode = 5;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set surface position offset
    /// <para>
    /// <br/>
    /// Specify the surface position offset relative to the position of the<br/>
    /// anchor on the anchor rectangle and the anchor on the surface. For<br/>
    /// example if the anchor of the anchor rectangle is at (x, y), the surface<br/>
    /// has the gravity bottom|right, and the offset is (ox, oy), the calculated<br/>
    /// surface position will be (x + ox, y + oy). The offset position of the<br/>
    /// surface is the one used for constraint testing. See<br/>
    /// set_constraint_adjustment.<br/>
    /// <br/>
    /// An example use case is placing a popup menu on top of a user interface<br/>
    /// element, while aligning the user interface element of the parent surface<br/>
    /// with some user interface element placed somewhere in the popup surface.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetOffset(int x, int y)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[2];
        args[0].i = x;
        args[1].i = y;

        const uint opcode = 6;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Continuously reconstrain the surface
    /// <para>
    /// <br/>
    /// When set reactive, the surface is reconstrained if the conditions used<br/>
    /// for constraining changed, e.g. the parent window moved.<br/>
    /// <br/>
    /// If the conditions changed and the popup was reconstrained, an<br/>
    /// xdg_popup.configure event is sent with updated geometry, followed by an<br/>
    /// xdg_surface.configure event.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetReactive()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 7;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set parent size
    /// <para>
    /// <br/>
    /// Set the parent window geometry the compositor should use when<br/>
    /// positioning the popup. The compositor may use this information to<br/>
    /// determine the future state the popup should be constrained using. If<br/>
    /// this doesn't match the dimension of the parent the popup is eventually<br/>
    /// positioned against, the behavior is undefined.<br/>
    /// <br/>
    /// The arguments are given in the surface-local coordinate space.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetParentSize(int parentWidth, int parentHeight)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[2];
        args[0].i = parentWidth;
        args[1].i = parentHeight;

        const uint opcode = 8;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set parent configure this is a response to
    /// <para>
    /// <br/>
    /// Set the serial of an xdg_surface.configure event this positioner will be<br/>
    /// used in response to. The compositor may use this information together<br/>
    /// with set_parent_size to determine what future state the popup should be<br/>
    /// constrained using.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetParentConfigure(uint serial)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].u = serial;

        const uint opcode = 9;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary> Creates a XdgPositioner wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new XdgPositioner instance.</returns>
    public static XdgPositioner Create(nint handle, WlDisplay? display = null)
    {
        return new XdgPositioner(handle);
    }
}
