// <auto-generated>
// This file was generated from river-xkb-config-v1.xml
// Stability: River
// Link: https://wayland.app/protocols/river-xkb-config-v1
// </auto-generated>

#nullable enable

namespace WaylandDotnet.River;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// river_xkb_keymap_v1
/// <para> xkbcommon keymap </para>
/// <para> Version: 2 </para>
/// <see>https://wayland.app/protocols/river-xkb-config-v1/#river_xkb_keymap_v1</see>
/// </summary>
public sealed partial class RiverXkbKeymapV1 : WaylandObject, IWaylandObjectFactory<RiverXkbKeymapV1>
{
    /// <summary> Wayland interface name for river_xkb_keymap_v1. </summary>
    public const string InterfaceName = "river_xkb_keymap_v1";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "river_xkb_keymap_v1";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 2;

    private bool disposed;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing river_xkb_keymap_v1 proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public RiverXkbKeymapV1(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary>
    /// Keymap creation succeeded
    /// <para>
    ///
    /// The keymap object was successfully created and may be used with the
    /// river_xkb_keyboard_v1.set_keymap request.
    /// 
    /// </para>
    /// </summary>
    public delegate void SuccessHandler();

    private SuccessHandler? _onSuccess;

    /// <summary>
    /// Keymap creation succeeded
    /// <para>
    ///
    /// The keymap object was successfully created and may be used with the
    /// river_xkb_keyboard_v1.set_keymap request.
    /// 
    /// </para>
    /// </summary>
    public event SuccessHandler? OnSuccess
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onSuccess += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onSuccess -= value;
        }
    }

    /// <summary>
    /// Keymap creation failed
    /// <para>
    ///
    /// The compositor failed to create a keymap from the given parameters.
    ///
    /// It is a protocol error to use this keymap object with
    /// river_xkb_keyboard_v1.set_keymap.
    /// 
    /// </para>
    /// </summary>
    public delegate void FailureHandler(string errorMsg);

    private FailureHandler? _onFailure;

    /// <summary>
    /// Keymap creation failed
    /// <para>
    ///
    /// The compositor failed to create a keymap from the given parameters.
    ///
    /// It is a protocol error to use this keymap object with
    /// river_xkb_keyboard_v1.set_keymap.
    /// 
    /// </para>
    /// </summary>
    public event FailureHandler? OnFailure
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onFailure += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onFailure -= value;
        }
    }

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to river_xkb_keymap_v1");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (RiverXkbKeymapV1)handle.Target!;

            switch (opcode)
            {
                case 0: // success
                    if (obj._onSuccess != null)
                    {
                        obj._onSuccess?.Invoke();
                    }
                    break;
                case 1: // failure
                    if (obj._onFailure != null)
                    {
                        var _errorMsg = Utf8StringMarshaller.ConvertToManaged(args[0].s) ?? string.Empty;
                        obj._onFailure?.Invoke(_errorMsg);
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }
    /// <summary>
    /// Destroy the keymap object
    /// <para>
    /// <br/>
    /// This request indicates that the client will no longer use the keymap<br/>
    /// object and that it may be safely destroyed.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary> Creates a RiverXkbKeymapV1 wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new RiverXkbKeymapV1 instance.</returns>
    public static RiverXkbKeymapV1 Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new RiverXkbKeymapV1(handle, display);
    }
}
