// <auto-generated>
// This file was generated from wlr-foreign-toplevel-management-unstable-v1.xml
// Stability: Wlr
// Link: https://wayland.app/protocols/wlr-foreign-toplevel-management-unstable-v1
// </auto-generated>

#nullable enable

namespace WaylandDotnet.Wlr;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// zwlr_foreign_toplevel_manager_v1
/// <para> list and control opened apps </para>
/// <para> Version: 3 </para>
/// <see>https://wayland.app/protocols/wlr-foreign-toplevel-management-unstable-v1/#zwlr_foreign_toplevel_manager_v1</see>
/// </summary>
public sealed partial class ZwlrForeignToplevelManagerV1 : WaylandObject, IWaylandObjectFactory<ZwlrForeignToplevelManagerV1>
{
    /// <summary> Wayland interface name for zwlr_foreign_toplevel_manager_v1. </summary>
    public const string InterfaceName = "zwlr_foreign_toplevel_manager_v1";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "zwlr_foreign_toplevel_manager_v1";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 3;

    private bool disposed;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing zwlr_foreign_toplevel_manager_v1 proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public ZwlrForeignToplevelManagerV1(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary>
    /// A toplevel has been created
    /// <para>
    ///
    /// This event is emitted whenever a new toplevel window is created. It
    /// is emitted for all toplevels, regardless of the app that has created
    /// them.
    ///
    /// All initial details of the toplevel(title, app_id, states, etc.) will
    /// be sent immediately after this event via the corresponding events in
    /// zwlr_foreign_toplevel_handle_v1.
    /// 
    /// </para>
    /// </summary>
    public delegate void ToplevelHandler(ZwlrForeignToplevelHandleV1 toplevel);

    private ToplevelHandler? _onToplevel;

    /// <summary>
    /// A toplevel has been created
    /// <para>
    ///
    /// This event is emitted whenever a new toplevel window is created. It
    /// is emitted for all toplevels, regardless of the app that has created
    /// them.
    ///
    /// All initial details of the toplevel(title, app_id, states, etc.) will
    /// be sent immediately after this event via the corresponding events in
    /// zwlr_foreign_toplevel_handle_v1.
    /// 
    /// </para>
    /// </summary>
    public event ToplevelHandler? OnToplevel
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onToplevel += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onToplevel -= value;
        }
    }

    /// <summary>
    /// The compositor has finished with the toplevel manager
    /// <para>
    ///
    /// This event indicates that the compositor is done sending events to the
    /// zwlr_foreign_toplevel_manager_v1. The server will destroy the object
    /// immediately after sending this request, so it will become invalid and
    /// the client should free any resources associated with it.
    /// 
    /// </para>
    /// </summary>
    public delegate void FinishedHandler();

    private FinishedHandler? _onFinished;

    /// <summary>
    /// The compositor has finished with the toplevel manager
    /// <para>
    ///
    /// This event indicates that the compositor is done sending events to the
    /// zwlr_foreign_toplevel_manager_v1. The server will destroy the object
    /// immediately after sending this request, so it will become invalid and
    /// the client should free any resources associated with it.
    /// 
    /// </para>
    /// </summary>
    public event FinishedHandler? OnFinished
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onFinished += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onFinished -= value;
        }
    }

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to zwlr_foreign_toplevel_manager_v1");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (ZwlrForeignToplevelManagerV1)handle.Target!;

            switch (opcode)
            {
                case 0: // toplevel
                    if (obj._onToplevel != null)
                    {
                        if (args[0].o == (WlObject*)IntPtr.Zero) throw new InvalidOperationException("Received null object for non-nullable argument 'toplevel'");
                        var _toplevel = new ZwlrForeignToplevelHandleV1((IntPtr)args[0].o, obj.Display!);
                        obj._onToplevel?.Invoke(_toplevel);
                    }
                    break;
                case 1: // finished
                    if (obj._onFinished != null)
                    {
                        obj._onFinished?.Invoke();
                        obj.disposed = true;
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }
    /// <summary>
    /// Stop sending events
    /// <para>
    /// <br/>
    /// Indicates the client no longer wishes to receive events for new toplevels.<br/>
    /// However the compositor may emit further toplevel_created events, until<br/>
    /// the finished event is emitted.<br/>
    /// <br/>
    /// The client must not send any more requests after this one.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Stop()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary> Creates a ZwlrForeignToplevelManagerV1 wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new ZwlrForeignToplevelManagerV1 instance.</returns>
    public static ZwlrForeignToplevelManagerV1 Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new ZwlrForeignToplevelManagerV1(handle, display);
    }
}
