// <auto-generated>
// This file was generated from river-libinput-config-v1.xml
// Stability: River
// Link: https://wayland.app/protocols/river-libinput-config-v1
// </auto-generated>

#nullable enable

namespace WaylandDotnet.River;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// river_libinput_config_v1
/// <para> libinput config global interface </para>
/// <para> Version: 2 </para>
/// <see>https://wayland.app/protocols/river-libinput-config-v1/#river_libinput_config_v1</see>
/// </summary>
public sealed partial class RiverLibinputConfigV1 : WaylandObject, IWaylandObjectFactory<RiverLibinputConfigV1>
{
    /// <summary> Wayland interface name for river_libinput_config_v1. </summary>
    public const string InterfaceName = "river_libinput_config_v1";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "river_libinput_config_v1";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 2;

    private bool disposed;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing river_libinput_config_v1 proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public RiverLibinputConfigV1(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary>  </summary>
    public enum Error : uint
    {
        /// <summary>
        /// invalid enum value or similar
        /// </summary>
        InvalidArg = 0,
        /// <summary>
        ///
        /// </summary>
        InvalidDestroy = 1,
    }

    /// <summary>
    /// The server has finished with the object
    /// <para>
    ///
    /// This event indicates that the server will send no further events on this
    /// object. The client should destroy the object. See
    /// river_libinput_config_v1.destroy for more information.
    /// 
    /// </para>
    /// </summary>
    public delegate void FinishedHandler();

    private FinishedHandler? _onFinished;

    /// <summary>
    /// The server has finished with the object
    /// <para>
    ///
    /// This event indicates that the server will send no further events on this
    /// object. The client should destroy the object. See
    /// river_libinput_config_v1.destroy for more information.
    /// 
    /// </para>
    /// </summary>
    public event FinishedHandler? OnFinished
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onFinished += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onFinished -= value;
        }
    }

    /// <summary>
    /// New libinput device
    /// <para>
    ///
    /// A new libinput device has been created. Not every river_input_device_v1
    /// is necessarily a libinput device as well.
    /// 
    /// </para>
    /// </summary>
    public delegate void LibinputDeviceHandler(RiverLibinputDeviceV1 id);

    private LibinputDeviceHandler? _onLibinputDevice;

    /// <summary>
    /// New libinput device
    /// <para>
    ///
    /// A new libinput device has been created. Not every river_input_device_v1
    /// is necessarily a libinput device as well.
    /// 
    /// </para>
    /// </summary>
    public event LibinputDeviceHandler? OnLibinputDevice
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onLibinputDevice += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onLibinputDevice -= value;
        }
    }

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to river_libinput_config_v1");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (RiverLibinputConfigV1)handle.Target!;

            switch (opcode)
            {
                case 0: // finished
                    if (obj._onFinished != null)
                    {
                        obj._onFinished?.Invoke();
                    }
                    break;
                case 1: // libinput_device
                    if (obj._onLibinputDevice != null)
                    {
                        if (args[0].o == (WlObject*)IntPtr.Zero) throw new InvalidOperationException("Received null object for non-nullable argument 'id'");
                        var _id = new RiverLibinputDeviceV1((IntPtr)args[0].o, obj.Display!);
                        obj._onLibinputDevice?.Invoke(_id);
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }
    /// <summary>
    /// Stop sending events
    /// <para>
    /// <br/>
    /// This request indicates that the client no longer wishes to receive<br/>
    /// events on this object.<br/>
    /// <br/>
    /// The Wayland protocol is asynchronous, which means the server may send<br/>
    /// further events until the stop request is processed. The client must wait<br/>
    /// for a river_libinput_config_v1.finished event before destroying this<br/>
    /// object.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Stop()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Destroy the river_libinput_config_v1 object
    /// <para>
    /// <br/>
    /// This request should be called after the finished event has been received<br/>
    /// to complete destruction of the object.<br/>
    /// <br/>
    /// It is a protocol error to make this request before the finished event<br/>
    /// has been received.<br/>
    /// <br/>
    /// If a client wishes to destroy this object it should send a<br/>
    /// river_libinput_config_v1.stop request and wait for a<br/>
    /// river_libinput_config_v1.finished event. Once the finished event is<br/>
    /// received it is safe to destroy this object and any other objects created<br/>
    /// through this interface.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary>
    /// Create a acceleration config
    /// <para>
    /// <br/>
    /// Create a acceleration config which can be applied<br/>
    /// with river_libinput_device_v1.apply_accel_config.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe RiverLibinputAccelConfigV1 CreateAccelConfig(uint profile)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[2];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].u = profile;

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.RiverLibinputAccelConfigV1,
            (uint)WaylandInterfaces.RiverLibinputAccelConfigV1->Version,
            0,
            (nint)args
        );

        return new RiverLibinputAccelConfigV1(newProxy, Display);
    }

    /// <summary> Creates a RiverLibinputConfigV1 wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new RiverLibinputConfigV1 instance.</returns>
    public static RiverLibinputConfigV1 Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new RiverLibinputConfigV1(handle, display);
    }
}
