// <auto-generated>
// This file was generated from river-layer-shell-v1.xml
// Stability: River
// Link: https://wayland.app/protocols/river-layer-shell-v1
// </auto-generated>

#nullable enable

namespace WaylandDotnet.River;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// river_layer_shell_v1
/// <para> river layer shell global interface </para>
/// <para> Version: 1 </para>
/// <see>https://wayland.app/protocols/river-layer-shell-v1/#river_layer_shell_v1</see>
/// </summary>
public sealed partial class RiverLayerShellV1 : WaylandObject, IWaylandObjectFactory<RiverLayerShellV1>
{
    /// <summary> Wayland interface name for river_layer_shell_v1. </summary>
    public const string InterfaceName = "river_layer_shell_v1";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "river_layer_shell_v1";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 1;

    private bool disposed;

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing river_layer_shell_v1 proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public RiverLayerShellV1(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary>  </summary>
    public enum Error : uint
    {
        /// <summary>
        /// the layer_shell_output/seat object was already created.
        /// </summary>
        ObjectAlreadyCreated = 0,
    }

    /// <summary>
    /// Destroy the river_layer_shell_v1 object
    /// <para>
    /// <br/>
    /// This request indicates that the client will no longer use the<br/>
    /// river_layer_shell_v1 object.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary>
    /// Get layer shell output state
    /// <para>
    /// <br/>
    /// It is a protocol error to make this request more than once for a given<br/>
    /// river_output_v1 object.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe RiverLayerShellOutputV1 GetOutput(RiverOutputV1 output)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[2];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].o = (WlObject*)(output?.Handle ?? IntPtr.Zero);

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.RiverLayerShellOutputV1,
            (uint)WaylandInterfaces.RiverLayerShellOutputV1->Version,
            0,
            (nint)args
        );

        return new RiverLayerShellOutputV1(newProxy, Display);
    }

    /// <summary>
    /// Get layer shell seat state
    /// <para>
    /// <br/>
    /// It is a protocol error to make this request more than once for a given<br/>
    /// river_seat_v1 object.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe RiverLayerShellSeatV1 GetSeat(RiverSeatV1 seat)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[2];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].o = (WlObject*)(seat?.Handle ?? IntPtr.Zero);

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.RiverLayerShellSeatV1,
            (uint)WaylandInterfaces.RiverLayerShellSeatV1->Version,
            0,
            (nint)args
        );

        return new RiverLayerShellSeatV1(newProxy, Display);
    }

    /// <summary> Creates a RiverLayerShellV1 wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new RiverLayerShellV1 instance.</returns>
    public static RiverLayerShellV1 Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new RiverLayerShellV1(handle, display);
    }
}
