// <auto-generated>
// This file was generated from wlr-output-management-unstable-v1.xml
// Stability: Wlr
// Link: https://wayland.app/protocols/wlr-output-management-unstable-v1
// </auto-generated>

#nullable enable

namespace WaylandDotnet.Wlr;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// zwlr_output_head_v1
/// <para> output device </para>
/// <para> Version: 4 </para>
/// <see>https://wayland.app/protocols/wlr-output-management-unstable-v1/#zwlr_output_head_v1</see>
/// </summary>
public sealed partial class ZwlrOutputHeadV1 : WaylandObject, IWaylandObjectFactory<ZwlrOutputHeadV1>
{
    /// <summary> Wayland interface name for zwlr_output_head_v1. </summary>
    public const string InterfaceName = "zwlr_output_head_v1";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "zwlr_output_head_v1";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 4;

    private bool disposed;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing zwlr_output_head_v1 proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public ZwlrOutputHeadV1(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary>  </summary>
    public enum AdaptiveSyncState : uint
    {
        /// <summary>
        /// adaptive sync is disabled
        /// </summary>
        Disabled = 0,
        /// <summary>
        /// adaptive sync is enabled
        /// </summary>
        Enabled = 1,
    }

    /// <summary>
    /// Head name
    /// <para>
    ///
    /// This event describes the head name.
    ///
    /// The naming convention is compositor defined, but limited to alphanumeric
    /// characters and dashes (-). Each name is unique among all wlr_output_head
    /// objects, but if a wlr_output_head object is destroyed the same name may
    /// be reused later. The names will also remain consistent across sessions
    /// with the same hardware and software configuration.
    ///
    /// Examples of names include 'HDMI-A-1', 'WL-1', 'X11-1', etc. However, do
    /// not assume that the name is a reflection of an underlying DRM
    /// connector, X11 connection, etc.
    ///
    /// If this head matches a wl_output, the wl_output.name event must report
    /// the same name.
    ///
    /// The name event is sent after a wlr_output_head object is created. This
    /// event is only sent once per object, and the name does not change over
    /// the lifetime of the wlr_output_head object.
    /// 
    /// </para>
    /// </summary>
    public delegate void NameHandler(string name);

    private NameHandler? _onName;

    /// <summary>
    /// Head name
    /// <para>
    ///
    /// This event describes the head name.
    ///
    /// The naming convention is compositor defined, but limited to alphanumeric
    /// characters and dashes (-). Each name is unique among all wlr_output_head
    /// objects, but if a wlr_output_head object is destroyed the same name may
    /// be reused later. The names will also remain consistent across sessions
    /// with the same hardware and software configuration.
    ///
    /// Examples of names include 'HDMI-A-1', 'WL-1', 'X11-1', etc. However, do
    /// not assume that the name is a reflection of an underlying DRM
    /// connector, X11 connection, etc.
    ///
    /// If this head matches a wl_output, the wl_output.name event must report
    /// the same name.
    ///
    /// The name event is sent after a wlr_output_head object is created. This
    /// event is only sent once per object, and the name does not change over
    /// the lifetime of the wlr_output_head object.
    /// 
    /// </para>
    /// </summary>
    public event NameHandler? OnName
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onName += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onName -= value;
        }
    }

    /// <summary>
    /// Head description
    /// <para>
    ///
    /// This event describes a human-readable description of the head.
    ///
    /// The description is a UTF-8 string with no convention defined for its
    /// contents. Examples might include 'Foocorp 11" Display' or 'Virtual X11
    /// output via :1'. However, do not assume that the name is a reflection of
    /// the make, model, serial of the underlying DRM connector or the display
    /// name of the underlying X11 connection, etc.
    ///
    /// If this head matches a wl_output, the wl_output.description event must
    /// report the same name.
    ///
    /// The description event is sent after a wlr_output_head object is created.
    /// This event is only sent once per object, and the description does not
    /// change over the lifetime of the wlr_output_head object.
    /// 
    /// </para>
    /// </summary>
    public delegate void DescriptionHandler(string description);

    private DescriptionHandler? _onDescription;

    /// <summary>
    /// Head description
    /// <para>
    ///
    /// This event describes a human-readable description of the head.
    ///
    /// The description is a UTF-8 string with no convention defined for its
    /// contents. Examples might include 'Foocorp 11" Display' or 'Virtual X11
    /// output via :1'. However, do not assume that the name is a reflection of
    /// the make, model, serial of the underlying DRM connector or the display
    /// name of the underlying X11 connection, etc.
    ///
    /// If this head matches a wl_output, the wl_output.description event must
    /// report the same name.
    ///
    /// The description event is sent after a wlr_output_head object is created.
    /// This event is only sent once per object, and the description does not
    /// change over the lifetime of the wlr_output_head object.
    /// 
    /// </para>
    /// </summary>
    public event DescriptionHandler? OnDescription
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onDescription += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onDescription -= value;
        }
    }

    /// <summary>
    /// Head physical size
    /// <para>
    ///
    /// This event describes the physical size of the head. This event is only
    /// sent if the head has a physical size (e.g. is not a projector or a
    /// virtual device).
    ///
    /// The physical size event is sent after a wlr_output_head object is created. This
    /// event is only sent once per object, and the physical size does not change over
    /// the lifetime of the wlr_output_head object.
    /// 
    /// </para>
    /// </summary>
    public delegate void PhysicalSizeHandler(int width, int height);

    private PhysicalSizeHandler? _onPhysicalSize;

    /// <summary>
    /// Head physical size
    /// <para>
    ///
    /// This event describes the physical size of the head. This event is only
    /// sent if the head has a physical size (e.g. is not a projector or a
    /// virtual device).
    ///
    /// The physical size event is sent after a wlr_output_head object is created. This
    /// event is only sent once per object, and the physical size does not change over
    /// the lifetime of the wlr_output_head object.
    /// 
    /// </para>
    /// </summary>
    public event PhysicalSizeHandler? OnPhysicalSize
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onPhysicalSize += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onPhysicalSize -= value;
        }
    }

    /// <summary>
    /// Introduce a mode
    /// <para>
    ///
    /// This event introduces a mode for this head. It is sent once per
    /// supported mode.
    /// 
    /// </para>
    /// </summary>
    public delegate void ModeHandler(ZwlrOutputModeV1 mode);

    private ModeHandler? _onMode;

    /// <summary>
    /// Introduce a mode
    /// <para>
    ///
    /// This event introduces a mode for this head. It is sent once per
    /// supported mode.
    /// 
    /// </para>
    /// </summary>
    public event ModeHandler? OnMode
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onMode += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onMode -= value;
        }
    }

    /// <summary>
    /// Head is enabled or disabled
    /// <para>
    ///
    /// This event describes whether the head is enabled. A disabled head is not
    /// mapped to a region of the global compositor space.
    ///
    /// When a head is disabled, some properties (current_mode, position,
    /// transform and scale) are irrelevant.
    /// 
    /// </para>
    /// </summary>
    public delegate void EnabledHandler(int enabled);

    private EnabledHandler? _onEnabled;

    /// <summary>
    /// Head is enabled or disabled
    /// <para>
    ///
    /// This event describes whether the head is enabled. A disabled head is not
    /// mapped to a region of the global compositor space.
    ///
    /// When a head is disabled, some properties (current_mode, position,
    /// transform and scale) are irrelevant.
    /// 
    /// </para>
    /// </summary>
    public event EnabledHandler? OnEnabled
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onEnabled += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onEnabled -= value;
        }
    }

    /// <summary>
    /// Current mode
    /// <para>
    ///
    /// This event describes the mode currently in use for this head. It is only
    /// sent if the output is enabled.
    /// 
    /// </para>
    /// </summary>
    public delegate void CurrentModeHandler(ZwlrOutputModeV1 mode);

    private CurrentModeHandler? _onCurrentMode;

    /// <summary>
    /// Current mode
    /// <para>
    ///
    /// This event describes the mode currently in use for this head. It is only
    /// sent if the output is enabled.
    /// 
    /// </para>
    /// </summary>
    public event CurrentModeHandler? OnCurrentMode
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onCurrentMode += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onCurrentMode -= value;
        }
    }

    /// <summary>
    /// Current position
    /// <para>
    ///
    /// This events describes the position of the head in the global compositor
    /// space. It is only sent if the output is enabled.
    /// 
    /// </para>
    /// </summary>
    public delegate void PositionHandler(int x, int y);

    private PositionHandler? _onPosition;

    /// <summary>
    /// Current position
    /// <para>
    ///
    /// This events describes the position of the head in the global compositor
    /// space. It is only sent if the output is enabled.
    /// 
    /// </para>
    /// </summary>
    public event PositionHandler? OnPosition
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onPosition += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onPosition -= value;
        }
    }

    /// <summary>
    /// Current transformation
    /// <para>
    ///
    /// This event describes the transformation currently applied to the head.
    /// It is only sent if the output is enabled.
    /// 
    /// </para>
    /// </summary>
    public delegate void TransformHandler(int transform);

    private TransformHandler? _onTransform;

    /// <summary>
    /// Current transformation
    /// <para>
    ///
    /// This event describes the transformation currently applied to the head.
    /// It is only sent if the output is enabled.
    /// 
    /// </para>
    /// </summary>
    public event TransformHandler? OnTransform
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onTransform += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onTransform -= value;
        }
    }

    /// <summary>
    /// Current scale
    /// <para>
    ///
    /// This events describes the scale of the head in the global compositor
    /// space. It is only sent if the output is enabled.
    /// 
    /// </para>
    /// </summary>
    public delegate void ScaleHandler(WlFixed scale);

    private ScaleHandler? _onScale;

    /// <summary>
    /// Current scale
    /// <para>
    ///
    /// This events describes the scale of the head in the global compositor
    /// space. It is only sent if the output is enabled.
    /// 
    /// </para>
    /// </summary>
    public event ScaleHandler? OnScale
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onScale += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onScale -= value;
        }
    }

    /// <summary>
    /// The head has disappeared
    /// <para>
    ///
    /// This event indicates that the head is no longer available. The head
    /// object becomes inert. Clients should send a destroy request and release
    /// any resources associated with it.
    /// 
    /// </para>
    /// </summary>
    public delegate void FinishedHandler();

    private FinishedHandler? _onFinished;

    /// <summary>
    /// The head has disappeared
    /// <para>
    ///
    /// This event indicates that the head is no longer available. The head
    /// object becomes inert. Clients should send a destroy request and release
    /// any resources associated with it.
    /// 
    /// </para>
    /// </summary>
    public event FinishedHandler? OnFinished
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onFinished += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onFinished -= value;
        }
    }

    /// <summary>
    /// Head manufacturer
    /// <para>
    ///
    /// This event describes the manufacturer of the head.
    ///
    /// Together with the model and serial_number events the purpose is to
    /// allow clients to recognize heads from previous sessions and for example
    /// load head-specific configurations back.
    ///
    /// It is not guaranteed this event will be ever sent. A reason for that
    /// can be that the compositor does not have information about the make of
    /// the head or the definition of a make is not sensible in the current
    /// setup, for example in a virtual session. Clients can still try to
    /// identify the head by available information from other events but should
    /// be aware that there is an increased risk of false positives.
    ///
    /// If sent, the make event is sent after a wlr_output_head object is
    /// created and only sent once per object. The make does not change over
    /// the lifetime of the wlr_output_head object.
    ///
    /// It is not recommended to display the make string in UI to users. For
    /// that the string provided by the description event should be preferred.
    /// 
    /// </para>
    /// </summary>
    public delegate void MakeHandler(string make);

    private MakeHandler? _onMake;

    /// <summary>
    /// Head manufacturer
    /// <para>
    ///
    /// This event describes the manufacturer of the head.
    ///
    /// Together with the model and serial_number events the purpose is to
    /// allow clients to recognize heads from previous sessions and for example
    /// load head-specific configurations back.
    ///
    /// It is not guaranteed this event will be ever sent. A reason for that
    /// can be that the compositor does not have information about the make of
    /// the head or the definition of a make is not sensible in the current
    /// setup, for example in a virtual session. Clients can still try to
    /// identify the head by available information from other events but should
    /// be aware that there is an increased risk of false positives.
    ///
    /// If sent, the make event is sent after a wlr_output_head object is
    /// created and only sent once per object. The make does not change over
    /// the lifetime of the wlr_output_head object.
    ///
    /// It is not recommended to display the make string in UI to users. For
    /// that the string provided by the description event should be preferred.
    /// 
    /// </para>
    /// </summary>
    public event MakeHandler? OnMake
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onMake += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onMake -= value;
        }
    }

    /// <summary>
    /// Head model
    /// <para>
    ///
    /// This event describes the model of the head.
    ///
    /// Together with the make and serial_number events the purpose is to
    /// allow clients to recognize heads from previous sessions and for example
    /// load head-specific configurations back.
    ///
    /// It is not guaranteed this event will be ever sent. A reason for that
    /// can be that the compositor does not have information about the model of
    /// the head or the definition of a model is not sensible in the current
    /// setup, for example in a virtual session. Clients can still try to
    /// identify the head by available information from other events but should
    /// be aware that there is an increased risk of false positives.
    ///
    /// If sent, the model event is sent after a wlr_output_head object is
    /// created and only sent once per object. The model does not change over
    /// the lifetime of the wlr_output_head object.
    ///
    /// It is not recommended to display the model string in UI to users. For
    /// that the string provided by the description event should be preferred.
    /// 
    /// </para>
    /// </summary>
    public delegate void ModelHandler(string model);

    private ModelHandler? _onModel;

    /// <summary>
    /// Head model
    /// <para>
    ///
    /// This event describes the model of the head.
    ///
    /// Together with the make and serial_number events the purpose is to
    /// allow clients to recognize heads from previous sessions and for example
    /// load head-specific configurations back.
    ///
    /// It is not guaranteed this event will be ever sent. A reason for that
    /// can be that the compositor does not have information about the model of
    /// the head or the definition of a model is not sensible in the current
    /// setup, for example in a virtual session. Clients can still try to
    /// identify the head by available information from other events but should
    /// be aware that there is an increased risk of false positives.
    ///
    /// If sent, the model event is sent after a wlr_output_head object is
    /// created and only sent once per object. The model does not change over
    /// the lifetime of the wlr_output_head object.
    ///
    /// It is not recommended to display the model string in UI to users. For
    /// that the string provided by the description event should be preferred.
    /// 
    /// </para>
    /// </summary>
    public event ModelHandler? OnModel
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onModel += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onModel -= value;
        }
    }

    /// <summary>
    /// Head serial number
    /// <para>
    ///
    /// This event describes the serial number of the head.
    ///
    /// Together with the make and model events the purpose is to allow clients
    /// to recognize heads from previous sessions and for example load head-
    /// specific configurations back.
    ///
    /// It is not guaranteed this event will be ever sent. A reason for that
    /// can be that the compositor does not have information about the serial
    /// number of the head or the definition of a serial number is not sensible
    /// in the current setup. Clients can still try to identify the head by
    /// available information from other events but should be aware that there
    /// is an increased risk of false positives.
    ///
    /// If sent, the serial number event is sent after a wlr_output_head object
    /// is created and only sent once per object. The serial number does not
    /// change over the lifetime of the wlr_output_head object.
    ///
    /// It is not recommended to display the serial_number string in UI to
    /// users. For that the string provided by the description event should be
    /// preferred.
    /// 
    /// </para>
    /// </summary>
    public delegate void SerialNumberHandler(string serialNumber);

    private SerialNumberHandler? _onSerialNumber;

    /// <summary>
    /// Head serial number
    /// <para>
    ///
    /// This event describes the serial number of the head.
    ///
    /// Together with the make and model events the purpose is to allow clients
    /// to recognize heads from previous sessions and for example load head-
    /// specific configurations back.
    ///
    /// It is not guaranteed this event will be ever sent. A reason for that
    /// can be that the compositor does not have information about the serial
    /// number of the head or the definition of a serial number is not sensible
    /// in the current setup. Clients can still try to identify the head by
    /// available information from other events but should be aware that there
    /// is an increased risk of false positives.
    ///
    /// If sent, the serial number event is sent after a wlr_output_head object
    /// is created and only sent once per object. The serial number does not
    /// change over the lifetime of the wlr_output_head object.
    ///
    /// It is not recommended to display the serial_number string in UI to
    /// users. For that the string provided by the description event should be
    /// preferred.
    /// 
    /// </para>
    /// </summary>
    public event SerialNumberHandler? OnSerialNumber
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onSerialNumber += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onSerialNumber -= value;
        }
    }

    /// <summary>
    /// Current adaptive sync state
    /// <para>
    ///
    /// This event describes whether adaptive sync is currently enabled for
    /// the head or not. Adaptive sync is also known as Variable Refresh
    /// Rate or VRR.
    /// 
    /// </para>
    /// </summary>
    public delegate void AdaptiveSyncHandler(uint state);

    private AdaptiveSyncHandler? _onAdaptiveSync;

    /// <summary>
    /// Current adaptive sync state
    /// <para>
    ///
    /// This event describes whether adaptive sync is currently enabled for
    /// the head or not. Adaptive sync is also known as Variable Refresh
    /// Rate or VRR.
    /// 
    /// </para>
    /// </summary>
    public event AdaptiveSyncHandler? OnAdaptiveSync
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onAdaptiveSync += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onAdaptiveSync -= value;
        }
    }

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to zwlr_output_head_v1");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (ZwlrOutputHeadV1)handle.Target!;

            switch (opcode)
            {
                case 0: // name
                    if (obj._onName != null)
                    {
                        var _name = Utf8StringMarshaller.ConvertToManaged(args[0].s) ?? string.Empty;
                        obj._onName?.Invoke(_name);
                    }
                    break;
                case 1: // description
                    if (obj._onDescription != null)
                    {
                        var _description = Utf8StringMarshaller.ConvertToManaged(args[0].s) ?? string.Empty;
                        obj._onDescription?.Invoke(_description);
                    }
                    break;
                case 2: // physical_size
                    if (obj._onPhysicalSize != null)
                    {
                        var _width = args[0].i;
                        var _height = args[1].i;
                        obj._onPhysicalSize?.Invoke(_width, _height);
                    }
                    break;
                case 3: // mode
                    if (obj._onMode != null)
                    {
                        if (args[0].o == (WlObject*)IntPtr.Zero) throw new InvalidOperationException("Received null object for non-nullable argument 'mode'");
                        var _mode = new ZwlrOutputModeV1((IntPtr)args[0].o, obj.Display!);
                        obj._onMode?.Invoke(_mode);
                    }
                    break;
                case 4: // enabled
                    if (obj._onEnabled != null)
                    {
                        var _enabled = args[0].i;
                        obj._onEnabled?.Invoke(_enabled);
                    }
                    break;
                case 5: // current_mode
                    if (obj._onCurrentMode != null)
                    {
                        if (args[0].o == (WlObject*)IntPtr.Zero) throw new InvalidOperationException("Received null object for non-nullable argument 'mode'");
                        var _mode = new ZwlrOutputModeV1((IntPtr)args[0].o, obj.Display!);
                        obj._onCurrentMode?.Invoke(_mode);
                    }
                    break;
                case 6: // position
                    if (obj._onPosition != null)
                    {
                        var _x = args[0].i;
                        var _y = args[1].i;
                        obj._onPosition?.Invoke(_x, _y);
                    }
                    break;
                case 7: // transform
                    if (obj._onTransform != null)
                    {
                        var _transform = args[0].i;
                        obj._onTransform?.Invoke(_transform);
                    }
                    break;
                case 8: // scale
                    if (obj._onScale != null)
                    {
                        var _scale = args[0].f;
                        obj._onScale?.Invoke(_scale);
                    }
                    break;
                case 9: // finished
                    if (obj._onFinished != null)
                    {
                        obj._onFinished?.Invoke();
                    }
                    break;
                case 10: // make
                    if (obj._onMake != null)
                    {
                        var _make = Utf8StringMarshaller.ConvertToManaged(args[0].s) ?? string.Empty;
                        obj._onMake?.Invoke(_make);
                    }
                    break;
                case 11: // model
                    if (obj._onModel != null)
                    {
                        var _model = Utf8StringMarshaller.ConvertToManaged(args[0].s) ?? string.Empty;
                        obj._onModel?.Invoke(_model);
                    }
                    break;
                case 12: // serial_number
                    if (obj._onSerialNumber != null)
                    {
                        var _serialNumber = Utf8StringMarshaller.ConvertToManaged(args[0].s) ?? string.Empty;
                        obj._onSerialNumber?.Invoke(_serialNumber);
                    }
                    break;
                case 13: // adaptive_sync
                    if (obj._onAdaptiveSync != null)
                    {
                        var _state = args[0].u;
                        obj._onAdaptiveSync?.Invoke(_state);
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }
    /// <summary>
    /// Destroy the head object
    /// <para>
    /// <br/>
    /// This request indicates that the client will no longer use this head<br/>
    /// object.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Release()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary> Creates a ZwlrOutputHeadV1 wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new ZwlrOutputHeadV1 instance.</returns>
    public static ZwlrOutputHeadV1 Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new ZwlrOutputHeadV1(handle, display);
    }
}
