// <auto-generated>
// This file was generated from river-window-management-v1.xml
// Stability: River
// Link: https://wayland.app/protocols/river-window-management-v1
// </auto-generated>

#nullable enable

namespace WaylandDotnet.River;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// river_shell_surface_v1
/// <para> a surface for window manager UI </para>
/// <para> Version: 5 </para>
/// <see>https://wayland.app/protocols/river-window-management-v1/#river_shell_surface_v1</see>
/// </summary>
public sealed partial class RiverShellSurfaceV1 : WaylandObject, IWaylandObjectFactory<RiverShellSurfaceV1>
{
    /// <summary> Wayland interface name for river_shell_surface_v1. </summary>
    public const string InterfaceName = "river_shell_surface_v1";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "river_shell_surface_v1";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 5;

    private bool disposed;

    /// <summary> The display connection that owns this object. </summary>
    public new WlDisplay Display { get; private set; }

    /// <summary>
    /// Wraps an existing river_shell_surface_v1 proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object.</param>
    public RiverShellSurfaceV1(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary>  </summary>
    public enum Error : uint
    {
        /// <summary>
        /// shell surface already has a node object
        /// </summary>
        NodeExists = 0,
        /// <summary>
        /// failed to commit the surface before the window manager commit
        /// </summary>
        NoCommit = 1,
    }

    /// <summary>
    /// Destroy the shell surface object
    /// <para>
    /// <br/>
    /// This request indicates that the client will no longer use the shell<br/>
    /// surface object and that it may be safely destroyed.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary>
    /// Get the shell surface's render list node
    /// <para>
    /// <br/>
    /// Get the node in the render list corresponding to the shell surface.<br/>
    /// <br/>
    /// It is a protocol error to make this request more than once for a single<br/>
    /// shell surface.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe RiverNodeV1 GetNode()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].o = (WlObject*)IntPtr.Zero;

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.RiverNodeV1,
            (uint)WaylandInterfaces.RiverNodeV1->Version,
            0,
            (nint)args
        );

        return new RiverNodeV1(newProxy);
    }

    /// <summary>
    /// Sync next surface commit to window manager commit
    /// <para>
    /// <br/>
    /// Synchronize application of the next wl_surface.commit request on the<br/>
    /// shell surface with rest of the rendering state atomically applied with<br/>
    /// the next river_window_manager_v1.render_finish request.<br/>
    /// <br/>
    /// The client must make a wl_surface.commit request on the shell surface<br/>
    /// after this request and before the render_finish request, failure to do<br/>
    /// so is a protocol error.<br/>
    /// <br/>
    /// This request modifies rendering state and may only be made as part of a<br/>
    /// render sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SyncNextCommit()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary> Creates a RiverShellSurfaceV1 wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new RiverShellSurfaceV1 instance.</returns>
    public static RiverShellSurfaceV1 Create(nint handle, WlDisplay? display = null)
    {
        ArgumentNullException.ThrowIfNull(display);
        return new RiverShellSurfaceV1(handle, display);
    }
}
