// <auto-generated>
// This file was generated from river-window-management-v1.xml
// Stability: River
// Link: https://wayland.app/protocols/river-window-management-v1
// </auto-generated>

#nullable enable

namespace WaylandDotnet.River;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// river_node_v1
/// <para> a node in the render list </para>
/// <para> Version: 5 </para>
/// <see>https://wayland.app/protocols/river-window-management-v1/#river_node_v1</see>
/// </summary>
public sealed partial class RiverNodeV1 : WaylandObject, IWaylandObjectFactory<RiverNodeV1>
{
    /// <summary> Wayland interface name for river_node_v1. </summary>
    public const string InterfaceName = "river_node_v1";
    /// <summary> Static interface name used by <see cref="IWaylandObjectFactory{T}"/>. </summary>
    public static string _StaticInterfaceName => "river_node_v1";
    /// <summary> Interface version supported by this binding. </summary>
    public const int InterfaceVersion = 5;

    private bool disposed;

    /// <summary>
    /// Wraps an existing river_node_v1 proxy handle.
    /// </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    public RiverNodeV1(IntPtr handle)
    {
        Handle = handle;
    }
    /// <summary>
    /// Destroy the decoration object
    /// <para>
    /// <br/>
    /// This request indicates that the client will no longer use the node<br/>
    /// object and that it may be safely destroyed.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
        disposed = true;
    }

    /// <summary>
    /// Set absolute position of the node
    /// <para>
    /// <br/>
    /// Set the absolute position of the node in the compositor's logical<br/>
    /// coordinate space. The x and y coordinates may be positive or negative.<br/>
    /// <br/>
    /// Note that the position of a river_window_v1 refers to the position of<br/>
    /// the window content and is unaffected by the presence of borders or<br/>
    /// decoration surfaces.<br/>
    /// <br/>
    /// If this request is never sent, the position of the node is undefined by<br/>
    /// this protocol and left up to the compositor.<br/>
    /// <br/>
    /// This request modifies rendering state and may only be made as part of a<br/>
    /// render sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetPosition(int x, int y)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[2];
        args[0].i = x;
        args[1].i = y;

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Place node above all other nodes
    /// <para>
    /// <br/>
    /// This request places the node above all other nodes in the compositor's<br/>
    /// render list.<br/>
    /// <br/>
    /// This request modifies rendering state and may only be made as part of a<br/>
    /// render sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void PlaceTop()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Place node below all other nodes
    /// <para>
    /// <br/>
    /// This request places the node below all other nodes in the compositor's<br/>
    /// render list.<br/>
    /// <br/>
    /// This request modifies rendering state and may only be made as part of a<br/>
    /// render sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void PlaceBottom()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 3;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Place node above another node
    /// <para>
    /// <br/>
    /// This request places the node directly above another node in the<br/>
    /// compositor's render list.<br/>
    /// <br/>
    /// Attempting to place a node above itself has no effect.<br/>
    /// <br/>
    /// Given nodes A, B, C currently rendered in that order with C on top<br/>
    /// and A on the bottom, the following example demonstrates the behavior<br/>
    /// of this request and the meaning of "directly above":<br/>
    /// <br/>
    /// 1. A.place_above(C) -&gt; B, C, A<br/>
    /// 2. A.place_above(B) -&gt; B, A, C<br/>
    /// 3. B.place_above(A) -&gt; A, B, C<br/>
    /// <br/>
    /// This request modifies rendering state and may only be made as part of a<br/>
    /// render sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void PlaceAbove(RiverNodeV1 other)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].o = (WlObject*)(other?.Handle ?? IntPtr.Zero);

        const uint opcode = 4;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Place node below another node
    /// <para>
    /// <br/>
    /// This request places the node directly below another node in the<br/>
    /// compositor's render list.<br/>
    /// <br/>
    /// Attempting to place a node below itself has no effect.<br/>
    /// <br/>
    /// Given nodes A, B, C currently rendered in that order with C on top<br/>
    /// and A on the bottom, the following example demonstrates the behavior<br/>
    /// of this request and the meaning of "directly below":<br/>
    /// <br/>
    /// 1. C.place_below(A) -&gt; C, A, B<br/>
    /// 2. C.place_below(B) -&gt; A, C, B<br/>
    /// 3. B.place_below(C) -&gt; A, B, C<br/>
    /// <br/>
    /// This request modifies rendering state and may only be made as part of a<br/>
    /// render sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void PlaceBelow(RiverNodeV1 other)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].o = (WlObject*)(other?.Handle ?? IntPtr.Zero);

        const uint opcode = 5;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary> Creates a RiverNodeV1 wrapper from an existing proxy handle. </summary>
    /// <param name="handle">The native Wayland proxy handle.</param>
    /// <param name="display">The display connection that owns this object, when required.</param>
    /// <returns>A new RiverNodeV1 instance.</returns>
    public static RiverNodeV1 Create(nint handle, WlDisplay? display = null)
    {
        return new RiverNodeV1(handle);
    }
}
